package com.terrier.finances.gestion.ui.login.ui;

import com.terrier.finances.gestion.ui.communs.abstrait.AbstractUIComponent;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

import elemental.events.KeyboardEvent.KeyCode;

/**
 * Page de login
 * @author vzwingma
 *
 */
public class Login extends AbstractUIComponent<LoginController> {

	@AutoGenerated
	private GridLayout mainLayout;
	@AutoGenerated
	private VerticalLayout versionLayout;
	@AutoGenerated
	private Label labelBuildTime;
	@AutoGenerated
	private Label labelVersion;
	@AutoGenerated
	private Label labelVersionComptes;	
	@AutoGenerated
	private Label labelVersionOperations;	
	@AutoGenerated
	private Label labelVersionParametres;	
	@AutoGenerated
	private Label labelVersionUtilisateurs;	
	
	@AutoGenerated
	private VerticalLayout verticalLayout2;
	@AutoGenerated
	private VerticalLayout authlLayout;
	@AutoGenerated
	private VerticalLayout verticalLayout1;
	@AutoGenerated
	private Button buttonConnexion;
	@AutoGenerated
	private PasswordField passwordField;
	@AutoGenerated
	private TextField textLogin;
	@AutoGenerated
	private Label label1;
	/**
	 * 
	 */
	private static final long serialVersionUID = -8912123300643969099L;

	private static final String LOGIN_STYLE = "versionLabel";
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public Login() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		// Start
		startControleur();
	}


	/**
	 * @return the buttonConnexion
	 */
	public Button getButtonConnexion() {
		return buttonConnexion;
	}

	/**
	 * @return the passwordField
	 */
	public PasswordField getPasswordField() {
		return passwordField;
	}

	/**
	 * @return the textLogin
	 */
	public TextField getTextLogin() {
		return textLogin;
	}

	/* (non-Javadoc)
	 * @see com.terrier.finances.gestion.ui.components.AbstractUIComponent#getControleur()
	 */
	@Override
	public LoginController createControleur() {
		return new LoginController(this);
	}

	/**
	 * @return the labelBuildTime
	 */
	public Label getLabelBuildTime() {
		return labelBuildTime;
	}

	/**
	 * @return the labelVersion
	 */
	public Label getLabelVersion() {
		return labelVersion;
	}

	
	
	@AutoGenerated
	private GridLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new GridLayout();
		mainLayout.setStyleName("fondbleu");
		mainLayout.setSizeFull();
		mainLayout.setMargin(false);
		mainLayout.setColumns(3);
		mainLayout.setRows(3);

		// top-level component properties
		setSizeFull();

		// AuthlLayout
		authlLayout = buildAuthlLayout();
		mainLayout.addComponent(authlLayout, 1, 1);
		mainLayout.setComponentAlignment(authlLayout, new Alignment(48));

		// verticalLayout_2
		verticalLayout2 = new VerticalLayout();
		verticalLayout2.setWidth("150px");
		verticalLayout2.setHeight("-1px");
		verticalLayout2.setMargin(false);
		mainLayout.addComponent(verticalLayout2, 0, 2);
		mainLayout.setComponentAlignment(verticalLayout2, new Alignment(9));

		// VersionLayout
		versionLayout = buildVersionLayout();
		mainLayout.addComponent(versionLayout, 2, 2);
		mainLayout.setComponentAlignment(versionLayout, new Alignment(10));

		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildAuthlLayout() {
		// common part: create layout
		authlLayout = new VerticalLayout();
		authlLayout.setStyleName("loginLayout");
		authlLayout.setWidth("-1px");
		authlLayout.setHeight("-1px");
		authlLayout.setMargin(false);
		authlLayout.setSpacing(true);

		// label_1
		label1 = new Label();
		label1.setStyleName("login-header");
		label1.setWidth("200px");
		label1.setHeight("-1px");
		label1.setValue("  Authentification");
		authlLayout.addComponent(label1);
		authlLayout.setComponentAlignment(label1, new Alignment(48));

		// verticalLayout_1
		verticalLayout1 = buildVerticalLayout1();
		authlLayout.addComponent(verticalLayout1);
		authlLayout.setComponentAlignment(verticalLayout1, new Alignment(48));

		return authlLayout;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout1() {
		// common part: create layout
		verticalLayout1 = new VerticalLayout();
		verticalLayout1.setWidthUndefined();
		verticalLayout1.setHeight("200px");
		verticalLayout1.setMargin(false);

		// textLogin
		textLogin = new TextField();
		textLogin.setCaption("Login");
		textLogin.setDescription("Entrer le login");
		textLogin.setSizeFull();
		textLogin.setHeightUndefined();
		textLogin.setId("login");
		verticalLayout1.addComponent(textLogin);

		// passwordField
		passwordField = new PasswordField();
		passwordField.setCaption("Mot de passe");
		passwordField.setDescription("Entrer le mot de passe");
		passwordField.setSizeFull();
		passwordField.setHeightUndefined();
		passwordField.setId("password");
		verticalLayout1.addComponent(passwordField);

		// buttonConnexion
		buttonConnexion = new Button();
		buttonConnexion.setClickShortcut(KeyCode.ENTER);
		buttonConnexion.setStyleName("primary");
		buttonConnexion.setCaption("Connexion");
		buttonConnexion.setWidth("145px");
		buttonConnexion.setHeightUndefined();
		verticalLayout1.addComponent(buttonConnexion);
		verticalLayout1.setComponentAlignment(buttonConnexion, new Alignment(
				48));

		return verticalLayout1;
	}

	@AutoGenerated
	private VerticalLayout buildVersionLayout() {
		// common part: create layout
		versionLayout = new VerticalLayout();
		versionLayout.setWidth("250px");
		versionLayout.setHeightUndefined();
		versionLayout.setMargin(false);

		// labelVersion
		labelVersion = new Label();
		labelVersion.setStyleName(LOGIN_STYLE);
		labelVersion.setSizeUndefined();
		labelVersion.setValue("Version IHM : ");
		versionLayout.addComponent(labelVersion);

		// labelBuildTime
		labelBuildTime = new Label();
		labelBuildTime.setStyleName(LOGIN_STYLE);
		labelBuildTime.setSizeUndefined();
		labelBuildTime.setValue("Build : ");
		versionLayout.addComponent(labelBuildTime);

		// labelVersionServices
		labelVersionComptes= new Label();
		labelVersionComptes.setStyleName(LOGIN_STYLE);
		labelVersionComptes.setSizeUndefined();
		labelVersionComptes.setValue("Version µS Comptes : ");
		versionLayout.addComponent(labelVersionComptes);
		
		labelVersionOperations= new Label();
		labelVersionOperations.setStyleName(LOGIN_STYLE);
		labelVersionOperations.setSizeUndefined();
		labelVersionOperations.setValue("Version µS Opérations : ");
		versionLayout.addComponent(labelVersionOperations);
		
		labelVersionParametres= new Label();
		labelVersionParametres.setStyleName(LOGIN_STYLE);
		labelVersionParametres.setSizeUndefined();
		labelVersionParametres.setValue("Version µS Paramètres : ");
		versionLayout.addComponent(labelVersionParametres);
		
		labelVersionUtilisateurs= new Label();
		labelVersionUtilisateurs.setStyleName(LOGIN_STYLE);
		labelVersionUtilisateurs.setSizeUndefined();
		labelVersionUtilisateurs.setValue("Version µS Utilisateurs : ");
		versionLayout.addComponent(labelVersionUtilisateurs);		
		return versionLayout;
	}


	public Label getLabelVersionComptes() {
		return labelVersionComptes;
	}


	public Label getLabelVersionOperations() {
		return labelVersionOperations;
	}


	public Label getLabelVersionParametres() {
		return labelVersionParametres;
	}


	public Label getLabelVersionUtilisateurs() {
		return labelVersionUtilisateurs;
	}
}
