# Issu de la dernière image Tomcat 9
FROM tomcat:9.0.30-jdk11-openjdk
MAINTAINER vincent.zwingmann@gmail.com

# Copy de l'archive
COPY ihm.war /usr/local/tomcat/webapps/ihm.war

# Droit pour tous les users de Tomcat
RUN chmod a+r -R /usr/local/tomcat; \
    chmod 777 -R /usr/local/tomcat;